// 사용자 계정 (V14 베타 / 7계정)
// 시범 기사 3명 (사장님 catch: 조동욱 / 구현서 / 김현동) + 해피콜 1 + 사장님 1 + 원청 1 + 첫 로그인 시뮬 1

export const REGISTERED_USERS = [
  // 시범 기사 3명 (사장님 catch: 조동욱 / 구현서 / 김현동)
  {
    userId: "cho.dongwook",
    name: "조동욱",
    role: "engineer",
    engineerId: "E022",
    roleLabel: "기사님",
    roleIcon: "🔧",
    roleColor: "#10B981",
    phone: "010-9447-1547",
    password: "engineer1!",
    isFirstLogin: false,
  },
  {
    userId: "koo.hyunseo",
    name: "구현서",
    role: "engineer",
    engineerId: "E002",
    roleLabel: "기사님",
    roleIcon: "🔧",
    roleColor: "#10B981",
    phone: "010-7372-3524",
    password: "engineer1!",
    isFirstLogin: false,
  },
  {
    userId: "kim.hyundong",
    name: "김현동",
    role: "engineer",
    engineerId: "E011",
    roleLabel: "기사님",
    roleIcon: "🔧",
    roleColor: "#10B981",
    phone: "010-5057-2312",
    password: "engineer1!",
    isFirstLogin: false,
  },
  // 첫 로그인 시뮬
  {
    userId: "test.firstlogin",
    name: "임시 기사",
    role: "engineer",
    engineerId: "E099",
    roleLabel: "기사님",
    roleIcon: "🔧",
    roleColor: "#10B981",
    phone: "010-0000-0000",
    password: "temp1234",
    isFirstLogin: true,
  },
  // 해피콜 / 사장님 / 원청 (V13 호환 / 그대로 유지)
  {
    userId: "kim.jihye",
    name: "김지혜",
    role: "happycall",
    roleLabel: "해피콜 담당자",
    roleIcon: "📞",
    roleColor: "#7F77DD",
    phone: "010-3333-3333",
    password: "happycall1!",
    isFirstLogin: false,
  },
  {
    userId: "lee.ceo",
    name: "이대표",
    role: "admin",
    roleLabel: "사장님",
    roleIcon: "👔",
    roleColor: "#E91860",
    phone: "010-4444-4444",
    password: "admin1234!",
    isFirstLogin: false,
  },
  {
    userId: "kim.coolguy",
    name: "쿨가이",
    role: "principal",
    clientName: "쿨가이",
    roleLabel: "원청 사장님 (쿨가이)",
    roleIcon: "🏪",
    roleColor: "#FFB800",
    phone: "010-5555-5555",
    password: "cool1234!",
    isFirstLogin: false,
  },
];

export const ROLE_INFO = {
  engineer: { label: "기사님", icon: "🔧", color: "#10B981", description: "현장 작업 수행" },
  happycall: { label: "해피콜 담당자", icon: "📞", color: "#7F77DD", description: "고객 응대 + 배정" },
  admin: { label: "사장님", icon: "👔", color: "#E91860", description: "운영 총괄" },
  principal: { label: "원청 사장님", icon: "🏪", color: "#FFB800", description: "원청 회사 대표" },
};
