# 유솔N 주차 확정 스냅샷 설계 — 카드 집계 안정화

**작성**: 2026-07-20
**상태**: 설계 초안 · 사장님 결정 대기
**대체 대상**: Mig 184 (confirm-스탬프만) 방식 → 스냅샷 방식으로 전환

---

## [0] Mig 184 재검토 — 왜 스탬프만으론 부족

**Mig 184 로직**: confirm 시 청구 items 의 `company_received_at` 을 확정일로 일괄 스탬프 → 이월 소멸.

**사장님 실측 결과**: 7/13 확정 주차 카드 합계 2,865,597 → 864,369 축소.

**원인 재정의**:
- 주차 카드 집계 (`fetchJuneLiveWeeks`, `fetchWeekItemsByMonday`) = **라이브 SQL 쿼리** — 매 새로고침마다 현재 `task_items` 상태로 재계산.
- 이월분 필터 (`fetchCarryoverC2Items`) = `company_received_at IS NULL` 조건.
- Mig 184 로 스탬프 → 이월 소멸은 성공. 그러나 **같은 items 가 확정 주차 카드 집계에서도 빠짐** → 확정 주차 금액 축소.

즉 라이브 집계와 이월 소멸이 **같은 상태 컬럼**을 공유해서 서로 간섭.

**근본 해결**: 확정 주차는 **청구 시점의 스냅샷**을 저장·조회. 미확정 주차만 라이브 계산. `company_received_at` 은 이월 소멸용으로만 유지하고 확정 주차 카드 집계와 분리.

---

## [1] 신규 테이블 + 요약 컬럼 (2026-07-20 사장님 결정 반영)

### [1-A] `principal_weekly_remittances` 컬럼 추가 (요약 스냅샷)

```sql
ALTER TABLE principal_weekly_remittances
  ADD COLUMN snapshot_item_count int;         -- 확정 주차 청구 건수 (요약값)
```

- 요약값 = `remitted_amount` (기존, 회사 실수령) + `snapshot_item_count` (신규).
- 미확정 주차: NULL.
- 확정 주차: 확정 시각에 세팅. 건별 스냅샷 실패해도 이 값은 남아 카드 표시 가능.

### [1-B] 신규 테이블 `principal_weekly_remit_items` (건별 스냅샷)

주차 확정 시 그 주차 청구서 items (당주 + 이월) 을 row 1개씩 저장. 요약-only 확정(7/6 케이스)에서는 이 테이블에 0건.

```sql
CREATE TABLE principal_weekly_remit_items (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id                uuid NOT NULL REFERENCES tenants(id),
  remit_id                 uuid NOT NULL REFERENCES principal_weekly_remittances(id) ON DELETE CASCADE,
  task_item_id             uuid NOT NULL REFERENCES task_items(id),

  -- 금액 스냅샷 (확정 시점 값 고정)
  subtotal                 int  NOT NULL,          -- 유솔 정산금 (task_items.subtotal)
  net_amount               int,                     -- 네이버 정산원금 (task_items.net_amount)
  company_receive_amount   int  NOT NULL,          -- 회사 실수령 (분배 후) — 카드/엑셀 합계 소스

  -- 이월 구분
  is_carryover             boolean NOT NULL DEFAULT false,
  carryover_source_monday  date,                    -- 이월 시 원 정산주 KST 월요일, 당주면 NULL

  -- 원본 시각 스냅샷 (드릴인 표기용)
  naver_settled_at         timestamptz NOT NULL,

  captured_at              timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT remit_items_unique UNIQUE (remit_id, task_item_id)
);

CREATE INDEX idx_remit_items_by_remit ON principal_weekly_remit_items(remit_id);
CREATE INDEX idx_remit_items_by_item  ON principal_weekly_remit_items(task_item_id);
```

### 컬럼 근거
- **`subtotal`**: 원청 청구액 스냅샷. 사장님 화면 "유솔 정산금".
- **`net_amount`**: 정산원금 (네이버). 감사·재계산 대비.
- **`company_receive_amount`**: 카드 메인 합계·엑셀 합계 소스. `fetchCarryoverC2Items` 산식 `subtotal − 분배 principal` 결과값을 그대로 저장.
- **`is_carryover` / `carryover_source_monday`**: 드릴인 UI 이월 뱃지 렌더링 + 감사.
- **`naver_settled_at`**: 원본 정산 시각. 드릴인 정렬·표시용.

### 대안 (검토)
| 안 | 설명 | 장단 |
|---|---|---|
| **A. 위 신규 테이블** | remit_id 로 스냅샷 조회 | 정확·감사 명확. 옛 파일 소급 필요 |
| B. `task_items` 에 `snapshot_remit_id` 컬럼 추가 | 원본에 직접 링크 | 스키마 오염. 이월 원본과 당주 원본을 같은 컬럼에 못 담음 |
| C. JSON 필드로 `remit.items_snapshot` 통 저장 | remit 1 row 안에 JSON 배열 | 인덱스·조회 성능 열세. 감사·수정 어려움 |

→ **A 권장**.

---

## [2] confirm RPC 확장 (신규 Mig 185 가칭)

`confirm_principal_remittance` 본문:

1. 권한 검사 (기존)
2. `principal_weekly_remittances` row 잠금 + already_confirmed 가드 (기존)
3. **청구 items 계산** — `fetchCarryoverC2Items` + `fetchWeekItemsByMonday` 필터를 SQL 로 미러링:
   - `naver_settled_at AT TIME ZONE 'Asia/Seoul' :: date <= week_end`
   - `NOT is_canceled AND subtotal > 0`
   - `EXISTS payments.track = 'B'`
   - `tasks.status = '완료'`, `principal_id = v_row.principal_id`
   - `is_carryover` = `(settled_kst_date < v_row.week_start)`
4. **분배 금액 계산** — `subtotal − distributed_principal` (프론트 로직 SQL 이식):
   ```
   task_sub  = Σ (그 task 의 모든 active items subtotal)
   dist_prin = round(principal_excl_extra × subtotal / task_sub)
   company_receive = subtotal − dist_prin
   ```
5. **`principal_weekly_remit_items` INSERT** — 위 결과를 row 마다 저장
6. **`company_received_at` 스탬프** — 이월 소멸용 (Mig 184 로직) — 카드 집계와 분리됨
7. `confirmed_at`, `confirmed_by` 세팅 (기존)
8. 응답: `{ ok, id, confirmed_at, snapshot_count, stamped_count }`

**핵심**: 스냅샷은 confirm 시점 상태 고정. 이후 items 변경(net_amount 정정 등)이 있어도 카드는 스냅샷 값 유지.

---

## [3] 프론트 조회 로직 분기

### 대상 파일
- `src/lib/usolNWeeklyData.js` — `fetchJuneLiveWeeks`, `fetchWeekItemsByMonday`, `fetchCarryoverC2Items`

### 분기 규칙 (3단계 — 요약-only 폴백 포함)

```
IF 주차 remit.confirmed_at IS NOT NULL:
   items = principal_weekly_remit_items WHERE remit_id = remit.id
   IF items.count > 0:                     ← 건별 스냅샷 있음 (7/13 이후)
      → 카드 합계 = Σ company_receive_amount
      → 카드 건수 = items.count
      → 드릴인 리스트 = 스냅샷 row (task_item_id 로 task_items JOIN 부가정보)
      → 이월 배지 = is_carryover
   ELSE IF remit.snapshot_item_count IS NOT NULL:   ← 요약-only 폴백 (7/6)
      → 카드 합계 = remit.remitted_amount
      → 카드 건수 = remit.snapshot_item_count
      → 드릴인 = "건별 내역 복원 불가 · 요약값만 저장됨" 안내 배너
   ELSE:                                    ← 옛 데이터 (스냅샷 이전 확정)
      → 폴백: 라이브 계산 (기존 로직) — 회귀 리스크 있음, 조치 필요 여부 별도 판단
ELSE:                                       ← 미확정 주차
   기존 라이브 계산 (fetchWeekItemsByMonday + fetchCarryoverC2Items)
```

### 이월 부착 로직 변경
- 기존: 최신 미확정 주차(latest billing monday)에 이월 부착.
- 신규: 여전히 미확정 주차에만 부착. 확정 주차는 이월 신규 부착 없음 (스냅샷 고정).
- 어떤 items 가 이월 후보인가:
  - 스냅샷에 아직 잡히지 않은 것 = `company_received_at IS NULL AND NOT EXISTS remit_items WHERE task_item_id = ti.id`
  - 이 조건이 기존 `company_received_at IS NULL` 을 대체
- ⚠️ 이월 소멸은 여전히 `company_received_at` 스탬프에 의존. 스냅샷 존재만으론 이월 필터 못 함 (미확정 주차에도 스냅샷은 안 생기니 필요 없음)
- 실제 필터: `company_received_at IS NULL` 그대로 유지 (Mig 185 가 스탬프도 하니 자동 소멸)

---

## [4] 소급 (2026-07-20 사장님 결정 반영)

### 4-A) 7/6 확정분 (6/29~7/5) — **건별 스냅샷 (당주 115 · 이월 0)** ← 2026-07-20 정정

- **진실 소스 파일**: `C:\Users\butto\Downloads\유솔N_주정산_7월 1주차 (1).xlsx` (57,396 bytes)
- **요약 시트 확정 값**:
  - 네이버 건수: **115**
  - 정산원금: **9,631,792**
  - 유솔수수료(15%): 1,444,769
  - 실입금(85%): **8,187,023**
  - 당주 건수: **115** / 당주 정산원금: 9,631,792
  - 이월 건수: **0** / 이월 정산원금: 0
- **이중 수령 없음 확정** (사장님 대조 결과):
  - 이월 39건은 7/13 확정 시 1회만 수령 (통장 실입금 2,865,597 = 7/13 엑셀 실입금 정확 일치)
  - 7/6 이월 0건 = 7/6 통장 입금액 8,187,023에 이월 미포함 = 정합
- 옛 doc 값 폐기:
  - ~~`유솔N_주정산_7월 1주차.xlsx` (스페이스 O) = 121건 / 7,712,614~~ ← 이월 배포 후 재다운로드분, 실제 7/6 청구서 아님
  - ~~DB 역산 111건 / 7,922,450~~ ← 확정 후 데이터 변경으로 산출된 값, 참고 아님
- 건별 상세 시트: 116 rows = 헤더 + 115 rows (전부 `당주 정산`, `이전 미정산` 0건)
- **처리**:
  1. 엑셀 → 115건 파싱 → `product_order_id` 매칭 → `principal_weekly_remit_items` INSERT (전부 `is_carryover=false`, `carryover_source_monday=NULL`)
  2. `snapshot_item_count = 115` UPDATE
  3. **`company_received_at` 스탬프 대상 = 매칭된 당주 115건만** (사장님 지정) — 이월 없음
  4. `remitted_amount` 확인 — 현재 값과 엑셀 실입금 8,187,023 대조 (5원 차이 시 정정 or 유지 결정)

### 4-B) 7/13 확정분 (7/6~7/12) — **엑셀 기반 건별 스냅샷**

- 소스 파일 확인: **`C:\Users\butto\Downloads\유솔N_주정산_7월 2주차 (1).xlsx`** (2026-07-13 21:05).
- 사장님 spec: 53건 전부 스냅샷.
- 컬럼 매핑 (사장님 지시):
  - **"구분" 컬럼** → `is_carryover` 판정:
    - `"당주 정산"` → `is_carryover = false`, `carryover_source_monday = NULL`
    - `"이전 미정산 (M/D~M/D)"` → `is_carryover = true`, `carryover_source_monday = 파싱 M/D 월요일`
  - 다른 컬럼 (금액, task_item_id 매핑 키): 엑셀 헤더 확인 후 매핑 (아래 [4-B-1])

### 4-B-1) 엑셀 컬럼 파악 완료 (2026-07-20 · `scripts/diag-usoln-remit-excel-header.py`)

**시트 구조 2개**:

**시트 1 — "요약"** (2 rows × 10 cols):
| 컬럼 | 값 예시 | 매핑 |
|---|---|---|
| 정산주차 | `7월 2주차` | 참고 |
| 기간 | `7/6~7/12` | remit.week_start·week_end 대조 |
| 네이버 건수 | 53 | `snapshot_item_count` |
| 정산금액 | 3,371,291 | Σ subtotal 대조 |
| 유솔수수료(15%) | 505,694 | 참고 |
| 실입금(85%) | **2,865,597** | remit.remitted_amount 대조 |
| 당주 건수 | 14 | 참고 (`is_carryover=false` 카운트) |
| 당주 정산금액 | 1,016,906 | 참고 |
| 이월 건수 | 39 | 참고 (`is_carryover=true` 카운트) |
| 이월 정산금액 | 2,354,385 | 참고 |

**시트 2 — "건별 상세"** (54 rows = 헤더 + 53건 × 9 cols):
| 컬럼 | 값 예시 | 매핑 |
|---|---|---|
| 구분 | `당주 정산` / `이전 미정산 (6/8~6/14)` | `is_carryover` + `carryover_source_monday` |
| 정산완료일 | `2026-07-06` | `naver_settled_at` (KST 00:00 as timestamptz) |
| 상품주문번호 | `2026070144072831` | **task_items.product_order_id 매핑 키** |
| 소비자명 | `홍길동` | 참고 (매칭 검증) |
| 상품내용 | `설치_벽걸이` | 참고 |
| (6번째 컬럼) | (전부 NULL) | 미사용 |
| 정산금액 | 61,385 | `subtotal` |
| 유솔수수료(15%) | 9,208 | 참고 (subtotal × 0.15) |
| 실입금(85%) | 52,177 | `company_receive_amount` |

**핵심 매핑 확인**:
- 매칭 키 = `task_items.product_order_id`
- `is_carryover = (구분 != "당주 정산")`
- `carryover_source_monday` = `이전 미정산 (M/D~M/D)` 에서 M/D 파싱 → 그 날짜의 KST 월요일
  - 예: `"이전 미정산 (6/8~6/14)"` → `2026-06-08` (이미 월요일)
  - 예: `"이전 미정산 (6/22~6/28)"` → `2026-06-22` (이미 월요일)
- `net_amount` = 엑셀에 없음 → NULL 저장 (감사 시 task_items 조인)
- `naver_settled_at` = 엑셀 정산완료일(YYYY-MM-DD)을 KST 00:00 timestamptz로 저장
  - ⚠️ 원본 task_items.naver_settled_at 은 UTC timestamptz. 엑셀 값과 밀리초 단위까지 일치 못 함. 스냅샷은 엑셀 값(00:00 KST) 사용

**소급 스크립트 계획**: `scripts/backfill-remit-items-7_13.cjs`
1. 엑셀 시트 2 파싱 → 53 rows
2. `product_order_id` in 배열 → `task_items` SELECT
3. 매칭 성공: `principal_weekly_remit_items` INSERT
4. 매칭 실패: 리포트 출력
5. 요약: `principal_weekly_remittances.snapshot_item_count = 53` UPDATE

### 4-B-2) 매핑 실패 케이스
- 엑셀 53건 중 task_item_id 매칭 실패 → 리포트만, 스냅샷 row 생성 안 함
- 이 경우 카드 합계 < 사장님 확정 값 (예: 3건 매칭 실패 → 50건 스냅샷 + 요약값 폴백 없음 → 카드 축소)
- 대안: 매칭 실패해도 `principal_weekly_remittances.snapshot_item_count = 53` + `remitted_amount` 는 원본 유지 → **카드는 요약값 표시** (건별 스냅샷 무시)
- **결정 요청** — 아래 [6]에 항목 추가

---

## [5] Mig 184 처리 결정

두 옵션:

| 옵션 | 설명 |
|---|---|
| **폐기** | Mig 184 파일 삭제, 스탬프 로직은 Mig 185 (confirm+snapshot) 내부에서만 실행 |
| **분리 유지** | Mig 184 는 순수 `company_received_at` 스탬프 헬퍼 함수로 재정의, Mig 185 가 호출 |

→ **폐기 권장**. 미실행 상태니 흔적 남기지 말고 단일 Mig 185 로 통합.

---

## [6] Say-once 원칙 대상 — 이번 세션 확정 결정

### 2026-07-20 사장님 결정 확정분 (Say-once 잠금)
- ✅ **7/6 진실 소스** — `유솔N_주정산_7월 1주차 (1).xlsx` (57,396 bytes) = 115건 / 실입금 8,187,023 / 이월 0. Downloads의 121건 파일은 이월 배포 후 재다운로드분, 실제 청구서 아님.
- ✅ **이중 수령 없음 확정** — 이월 39건은 7/13에 1회만 수령 (통장 2,865,597 정확 일치).
- ✅ **7/6·7/13 둘 다 건별 스냅샷** — 요약-only 폴백 불필요 (양쪽 모두 엑셀 있음). 다만 폴백 로직은 미래 대비로 코드에 유지.
- ✅ **7/6 스탬프 대상 = 당주 115건만** — 이월 0건이므로 자연.
- ✅ **7/13 엑셀 소스** — `유솔N_주정산_7월 2주차 (1).xlsx` (36,519 bytes). 건별 53건 (당주 14 + 이월 39).
- ✅ **is_carryover 판정** — 엑셀 "구분" 컬럼: `"당주 정산"` = false / `"이전 미정산 (M/D~M/D)"` = true + M/D 파싱.
- ✅ **테이블 이름**: `principal_weekly_remit_items` + `principal_weekly_remittances.snapshot_item_count` 추가.
- ✅ **엑셀 매핑 키**: `상품주문번호` → `task_items.product_order_id`.

### 잔여 결정 (사장님 답 대기 · 낮은 우선도)
- [ ] **엑셀 매핑 실패 시** — 리포트만 vs 요약값 폴백 (`snapshot_item_count`만 세팅, 카드는 실입금 표시) vs 수동 확정 화면 추가
  - 권장 초안: 리포트 출력 + `snapshot_item_count` 는 엑셀 원본 건수(115/53) 그대로 유지 → 프론트가 요약 폴백으로 렌더링 (건별 매칭 부분만 유실)
- [ ] **미확정→확정 스위치 원자성** — RPC 내부 단일 트랜잭션 (권장 · 기본 채택)
- [ ] **unconfirm 경로 지원 여부** — 현재 미지원. 신규도 미지원 유지 (스냅샷 삭제 위험) vs 신규 unconfirm RPC 추가
  - 권장 초안: 미지원 유지. 실수 확정 시 사장님이 직접 SQL 로 remit_items DELETE + confirmed_at NULL 정정
- [ ] **Mig 184 처리** — 폐기 (권장) — Mig 185가 confirm 로직 재정의로 덮어씀
- [ ] **적용 순서**: Mig 185 SQL → 프론트 분기 → 7/6 소급 → 7/13 소급 → 검증

---

## [7] 리스크·엣지 케이스

| 리스크 | 정도 | 대응 |
|---|---|---|
| 소급 엑셀 → task_item_id 매칭 실패 | 🟡 Med | 리포트 + 수동 확정 |
| 스냅샷 이후 원본 item 삭제/취소 | 🟢 Low | FK 참조 유지, `is_canceled` 변경돼도 스냅샷 값 유지 (설계 의도) |
| 확정 후 사장님이 청구 정정 필요 | 🟡 Med | unconfirm RPC 추가 결정 필요 (위 [6]) |
| 프론트 fetchJuneLiveWeeks 이월 부착 로직 리팩터 회귀 | 🔴 High | Safe-steps: 스냅샷 조회 분기 먼저 → 이월 부착 로직 나중, 각 단계 검증 |
| Mig 185 로직 vs 프론트 산식 미묘한 불일치 (round 순서 등) | 🟡 Med | 소급 시 프론트 재계산값과 대조. SQL round 는 프론트 `Math.round` 와 같은 결과 나오는지 검증 |
| 이월 필터의 `NOT EXISTS remit_items` 안 넣어도 되는지 검증 | 🟢 Low | 스탬프 = 이월 소멸이 유지되면 필요 없음 |

---

## 산출물

- 본 doc — 설계·결정 요청
- 사장님 결정 확정 후 다음 산출물 예정:
  - `db/migrations/185_confirm_remit_snapshot.sql` — 신규 테이블 + confirm RPC 확장 + Mig 184 폐기
  - `src/lib/usolNWeeklyData.js` 수정 — 확정 주차 스냅샷 조회 분기 추가
  - `scripts/backfill-remit-items-7_6-7_13.cjs` — 엑셀 → remit_items INSERT 스크립트

---

## 사장님 결정 요청

**[6] 항목 순서대로 하나씩 결정** 주시면 각 단계별 파일 생성·검증 진행.

특히 시급 결정:
1. 테이블 이름·스키마 (위 초안 그대로 OK 인지)
2. **엑셀 소스 파일 위치 알려주십시오** — 소급 매핑 산정 위해 컬럼 구조 사전 파악 필요
3. Mig 184 폐기 OK 인지
